from countystats/r-geo:1.1

MAINTAINER Geoffrey Arnold "geoffrey.arnold@alleghenycounty.us"

RUN  R -e "devtools::install_github('Allegheny-CountyStats/moveitAPI')" 

COPY moveit-download.R /
COPY moveit-transfer.R /